//user
export const SET_USER = "SET_USER";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const RESET_USER_STATUS = "RESET_USER_STATUS";
export const RESET_USER_ERROR = "RESET_USER_ERROR";

//Category
export const SET_CATEGORY = "SET_CATEGORY";
export const CHOOSE_CATEGORY = "CHOOSE_CATEGORY";
export const CLEAR_CHOSEN_CATEGORY = "CLEAR_CHOSEN_CATEGORY";
//product
export const SET_PRODUCT = "SET_PRODUCT";
export const FILTER_PRODUCT_BY_CATEGORY = "FILTER_PRODUCT_BY_CATEGORY";
export const CLEAR_FILTER_CATEGORY = "CLEAR_FILTER_CATEGORY";
//cart
export const ADD_TO_CART = "ADD_TO_CART";
export const UNAUTHENTICATED_ADD_TO_CART = "UNAUTHENTICATED_ADD_TO_CART";
export const SET_CART_LOGIN = "SET_CART_LOGIN";
export const SET_UNAUTHENTICATED_CART = "SET_UNAUTHENTICATED_CART";
export const CLEAR_CART = "CLEAR_CART";
//order
export const SET_ORDER_SUCCESS = "SET_ORDER_SUCCESS";
export const SET_ORDER_REQUEST = "SET_ORDER_REQUEST";
export const SET_ORDER_ERROR = "SET_ORDER_ERROR";
export const MARK_ORDER_STATUS_SUCCESS = "MARK_ORDER_STATUS_SUCCESS";
export const MARK_ORDER_STATUS_REQUEST = "MARK_ORDER_STATUS_REQUEST";
export const MARK_ORDER_STATUS_ERROR = "MARK_ORDER_STATUS_ERROR";
