export const SET_USER = "SET_USER";
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';

//Category
export const SET_CATEGORY = 'SET_CATEGORY';